name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: executing remote ssh commands using ssh key
      uses: appleboy/ssh-action@master
      with:
        host: 127.0.0.1
        username: roshu
        key: ${{ secrets.SSHKEY }}
        port: 22
        script: |
          env
          rm -rf cfntest
          git clone https://github.com/Roshanitft/cfntest.git
          cd cfntest
          sudo docker build -t test .
          sudo docker rm -f test
          sudo docker run -dit --name test98 -p 8080:8080 test
